import { useState } from 'react';
import { ChevronDownIcon, ChevronUpIcon } from 'lucide-react';

export const Privacy = () => {
    const [openSections, setOpenSections] = useState<number[]>([]);

    const toggleSection = (index: number) => {
        setOpenSections(prev =>
            prev.includes(index)
                ? prev.filter(i => i !== index)
                : [...prev, index]
        );
    };

    const sections = [
        { title: 'I. INFORMACIÓN GENERAL', content: 'Su privacidad y continua son muy importantes para nuestra Sociedad. Por ello, queremos asegurarnos de que conozca cómo salvaguardamos la integridad, privacidad y protección de sus datos personales, en apego a la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, publicada en el Diario Oficial de la Federación el día 5 de julio de 2010. Con el objetivo de que usted tenga pleno control y decisión sobre sus datos personales, le recomendamos leer atentamente la siguiente información.' },
        { title: 'II. PRINCIPIO DE INFORMACIÓN', content: 'Cada responsable le informa que posee, recaba o recabará de usted, los datos personales necesarios, principalmente para la adecuada realización de las operaciones y prestación de los servicios, así como para la celebración de los demás actos que cada responsable puede realizar conforme a la ley y sus estatutos sociales. Dichos datos personales pueden haber sido o pueden ser obtenidos de usted, ya sea personalmente, o bien, directamente por cualquier medio electrónico, óptico, sonoro, visual, o a través de cualquier otra tecnología. Los datos personales recabados o que se recaban podrán incluir, entre otros, los siguientes:\n\n(i) Datos de identificación y de contacto: nombre completo, dirección, teléfono de casa, celular y/o de trabajo, estado civil, firma, firma electrónica, correo electrónico, nombre de usuario y contraseña, dirección IP, R.F.C., C.U.R.P., lugar y fecha de nacimiento, edad, nombres de familiares, dependientes y beneficiarios, así como sus domicilios, entre otros.\n\n(ii) Datos laborales: ocupación, puesto, área o departamento, domicilio, teléfono y correo de trabajo, referencias laborales, referencias personales y referencias comerciales, entre otros.\n\n(iii) Datos personales sensibles: estado de salud, afiliación sindical y otros que pueden ser así considerados.' },
        { title: 'III. RESPONSABLE DEL TRATAMIENTO DE SUS DATOS PERSONALES', content: 'La entidad responsable del tratamiento de sus datos personales es BRALIZA SA DE CV con domicilio Gardenia 354, Col. Los Sabinos, Montemorelos, Nuevo León, 67515 con independencia del manejo que se haga en cada establecimiento de la empresa.' },
        { title: 'IV. FINALIDADES DEL TRATAMIENTO DE LOS DATOS PERSONALES', content: 'Sus datos personales serán utilizados para las siguientes aplicaciones (fines): La empresa responsable dará tratamiento de los datos personales recabados, para los siguientes fines:\n\n(i) La realización de todas y cada una de las operaciones y la prestación de los servicios, así como la celebración de los demás actos que cada establecimiento de la empresa responsable puede realizar conforme a la ley y sus estatutos sociales;\n\n(ii) La realización de encuestas, así como la creación e implementación de procesos analíticos y estadísticos necesarios o convenientes, relacionados con dichas operaciones, servicios y actos;\n\n(iii) La promoción de productos, servicios, beneficios adicionales, descuentos, promociones, bonificaciones, concursos, estudios de mercado, sorteos y publicidad en general, todo esto ofrecido por o relacionado con las responsables o terceros nacionales o extranjeros con quienes cualquiera de dichas responsables mantenga alianzas comerciales;\n\n(v) La realización de cualquier actividad complementaria o auxiliar necesaria para la realización de los fines anteriores;\n\n(Vi) La realización de consultas, investigaciones y revisiones en relación a cualquier queja o reclamación; y\n\n(vii) La puesta en contacto con usted para tratar cualquier tema relacionado con sus datos personales o con el presente aviso de privacidad.\n\nEl tratamiento de datos personales se limitará: (i) al cumplimiento de las finalidades previstas en este aviso de privacidad; y (ii) a fines distintos que resulten compatibles o análogos a los establecidos en este aviso de privacidad, sin que para ello se requiera obtener nuevamente, en su caso, el consentimiento del titular. Asimismo, el tratamiento de datos personales será el que resulte necesario, adecuado y relevante en relación con las finalidades previstas en este aviso de privacidad, así como con los fines distintos que resulten compatibles o análogos.' },
        { title: 'V. FINES', content: '• Compraventa de productos\n• Investigación y estudios de mercadeo\n• Envío de publicidad bajo cualquier medio de comunicación, incluyendo correo directo (mailing), banners y dispositivos móviles\n• Servicio a domicilio\n• Implementación de mejoras en productos y servicios\n• Estudios Socio-económicos y socio-demográficos\n• Procesos administrativos como devoluciones, facturaciones, históricos de compras, procesamiento de solicitudes, cobro, aclaraciones, investigación.\n• Programa Lealtad\n• Comunicar ofertas y promociones direccionadas\n• Invitaciones a eventos especiales y sorteos.\n• Atención al cliente, felicitaciones, mensajes de bienvenida.\n• Boletines de noticias y promociones' },
        { title: 'VI. DEPARTAMENTO DE DATOS PERSONALES', content: 'Para dar cumplimiento a lo ordenado por la Ley Federal de Protección de Datos Personales en Posesión de Particulares, la empresa responsable BRALIZA SA de CV designa como Departamento de datos personales, quien dará trámite a las solicitudes de los titulares, para el ejercicio de los derechos de acceso, rectificación, cancelación y oposición, así como limitación a el uso o divulgación de los datos y revocación del consentimiento, a la encargada de nómina y recursos humanos, y encargado de sistemas, quienes pueden ser contactados en el domicilio ubicado en Gardenia 354, Col. Los Sabinos, Montemorelos, Nuevo León.' },
        { title: 'VII. MEDIOS PARA EJERCER LOS DERECHOS DE ACCESO, RECTIFICACIÓN, CANCELACIÓN Y OPOSICIÓN', content: 'Sujeto a lo dispuesto en la Ley Federal de Protección de Datos Personales en Posesión de Particulares, a partir del 6 de Enero de 2011, el titular por sí o mediante representante legal debidamente acreditado, podrá ejercer sus derechos de acceso, rectificación, cancelación y oposición, formulando la solicitud respectiva a través de las unidades y los medios de atención de la responsable de que se trate, designados como "Departamento de datos personales" en este aviso de privacidad, a través de los medios, escritos, electrónicos o de otro tipo y conforme al procedimiento que dicho departamento de datos personales tenga establecido al efecto. El ejercicio de cualquiera de ellos no es requisito previo ni impide el ejercicio de otro. Para su conocimiento, cada uno de los referidos derechos, respectivamente le permite:\n\n(i) Acceder a sus datos personales que obren en poder del responsable, así como conocer el Aviso de Privacidad al que está sujeto el tratamiento. La responsable de que se trate pondrá a su disposición los datos personales, o bien expedirá copias simples, documentos electrónicos o cualquier otro medio. La entrega de los datos personales será gratuita, debiendo cubrir el titular únicamente los gastos justificados de envío o con el costo de reproducción en copias u otros formatos. Dicho derecho se ejercerá por el titular en forma gratuita, previa acreditación de su identidad ante el responsable de que se trate. No obstante, si el titular reitera su solicitud en un periodo menor a doce meses, los costos no serán mayores a tres días de Salario Mínimo General Vigente en el Distrito Federal a menos que existan modificaciones sustanciales al aviso de privacidad que motiven nuevas consultas.\n\n(ii) Rectificar cualquiera de sus datos personales que sea inexacto o incompleto.\n\n(iii) Cancelar sus datos personales. En caso de ser procedente la solicitud, los datos personales entrarán al período de bloqueo en el cual no podrán ser tratados. Una vez cancelado el dato se dará aviso a su titular.\n\n(iv) Oponerse en todo momento y por causa legítima al tratamiento de sus datos personales.' },
        { title: 'VIII. OPCIONES Y MEDIOS PARA EJERCER LOS DERECHOS DE LIMITAR EL USO O DIVULGACIÓN DE LOS DATOS Y MECANISMOS Y PROCEDIMIENTOS PARA REVOCAR EL CONSENTIMIENTO', content: 'Usted también podrá en cualquier momento: (i) optar por limitar el uso o divulgación de sus datos personales; o (ii) revocar su consentimiento para dar tratamiento a sus datos personales, en la inteligencia que todo tratamiento de datos personales estará sujeto al consentimiento de su titular, salvo las excepciones previstas por la Ley Federal de Protección de Datos Personales en Posesión de Particulares. Para ejercer cualquiera de dichos derechos, usted deberá formular la solicitud respectiva únicamente a través de las unidades y los medios de atención de la responsable de que se trate, designados como "Departamento de datos personales" en este aviso de privacidad, a través de los medios, escritos, electrónicos o de otro tipo y conforme al procedimiento que dicho departamento de datos personales tenga establecido al efecto.' },
        { title: 'IX. PROCEDIMIENTO Y MEDIO POR EL CUAL SE COMUNICARÁ DE CAMBIOS AL AVISO DE PRIVACIDAD', content: 'Nos reservamos el derecho de efectuar en cualquier momento cambios o modificaciones al presente aviso de privacidad, ya sea para la atención de novedades legislativas, regulatorias o jurisprudenciales, políticas internas, prácticas del mercado o por cualquier otra razón. Cualquier cambio que se realice a este aviso de privacidad, será incorporado al mismo por las responsables y será dado a conocer a través de cualquiera de los siguientes medios: (i) anuncios visibles en nuestros establecimientos o centros de atención a clientes; (ii) trípticos o folletos disponibles en nuestros establecimientos o centros de atención a clientes; o (iii) nuestra página de internet http://www.sensalon.com.mx' },
      ];

    return (
        <div className="flex-grow w-full h-full flex items-center justify-center bg-white mt-10">
            <div className="w-full h-full mx-auto bg-white rounded-lg  overflow-hidden">
                <div className="px-4 py-5 sm:p-6">
                    <h1 className="text-3xl font-bold text-gray-900 text-center mb-8">AVISO DE PRIVACIDAD BRALIZA SA DE CV</h1>
                    <div className="space-y-4 h-full w-full overflow-y-auto">
                        {sections.map((section, index) => (
                            <div key={index} className="border-b border-gray-200 pb-4">
                                <button
                                    className="flex justify-between items-center w-full text-left font-semibold text-gray-900 focus:outline-none"
                                    onClick={() => toggleSection(index)}
                                >
                                    <span>{section.title}</span>
                                    {openSections.includes(index) ? (
                                        <ChevronUpIcon className="h-5 w-5 text-gray-500" />
                                    ) : (
                                        <ChevronDownIcon className="h-5 w-5 text-gray-500" />
                                    )}
                                </button>
                                {openSections.includes(index) && (
                                    <div className="mt-2 text-gray-600 text-sm whitespace-pre-wrap">
                                        {section.content}
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};
